### ISSUE TITLE
Trouble with nested arrays

### ISSUE THREAD

**Issue by SteveNewhouse** [bohnman/squiggly-filter-jackson#11]
Hi there.  Great library- thanks for making it!

We have a response that is structured as follows:

```
{
    "meta": {
        "executionTime": 0.044,
        "code": 200,
        "requestId": "c8f4df96-d8df-460a-bad6-b0e325029e28-WM-LGA",
        "responseTime": 0.044,
        "timestamp": 1501711423,
    },
    "result": {
        "warnings": null,
        "errors": null,
        "pagination": null,
        "payload": [
            {
                "uuid": "58149996-a15a-4036-be86-6a3eb5d425dd",
                "createdOn": null,
                "updatedOn": null,
                "deletedOn": null,
            }
   }
}
```

We're using a default filter wrapper like this `"meta,result{%s}"`, so any filters passed in get substituted in.

I cannot figure out how to filter within the payload array.  I've tried all sorts of things, including `payload{uuid}`, `payload[uuid]`, `payload.uuid`, etc with no luck.  What am I missing?

**Comment by SteveNewhouse** [comment]
Note the result of the examples I showed is just no filtering at all.

**Comment by bohnman** [comment]
Could replace Squiggly initialization with the following substituting new ObjectMapper() with the object mapper you are using and then provide the result of the print statement?

```java
Squiggly.init(new ObjectMapper(), new RequestSquigglyContextProvider() {
            @Override
            protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
                System.out.printf("Filter: %s, Bean Class: %s\n", filter, beanClass.getName());
                return super.customizeFilter(filter, request, beanClass);
            }
        });
```

**Comment by jeffsegal** [comment]
We have a somewhat similar response format, except with one less level (e.g., instead of `result.payload` we just have `payload`). This means that if we wanted to filter on `createdOn`, our filter String would look like `**,result[createdOn]`.

I'm guessing you could do accommodate your additional level by using `**,result.payload[createdOn]`. The key is the `**` wildcard.

**Comment by bohnman** [comment]
Yes.  You can use customizeFilter to automatically wrap the filter from the query string with "**,result[]" so /some/url?fields=createdOn  becomes "**,result[createdOn]".  

Does this resolve your issue?

**Comment by SteveNewhouse** [comment]
Yes, including "**," does actually resolve this...  Thank you very much!
