### ISSUE TITLE
How to modify filters

### ISSUE THREAD

**Issue by sheldon-sminq** [bohnman/squiggly-filter-jackson#12]
We are using the squiggly filter for partial api responses, our base payload consists of a wrapper json

```
{
    "success": true,
    "httpCode": 200,
    "status": {
          //response data
    }
```

To use the filters we have to set **fields=status.fieldName** for this to work. Is there a way to include the status. by default so the api user can just use filter **fields=fieldName**?.

**Comment by sheldon-sminq** [comment]
got it to work

```
Squiggly.init(environment.getObjectMapper(), new RequestSquigglyContextProvider() {
            @Override
            protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
                return "status."+filter;
            }
        });
```

**Comment by bohnman** [comment]
@sheldon-sminq Did you mean to reopen this issue? I just checked and it still works in the current version.

**Comment by sheldon-sminq** [comment]
@bohnman the above for nested filters did not seem to work so i changed it to 

```
Squiggly.init(environment.getObjectMapper(), new RequestSquigglyContextProvider() {
            @Override
            protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
                StringBuilder filterBuilder = new StringBuilder();
                filterBuilder.append("status[").append(filter).append("]");
                return filterBuilder.toString();
            }
        });
```

**Comment by sheldon-sminq** [comment]
now things are working fine.

**Comment by bohnman** [comment]
@sheldon-sminq   Right.  The dot syntax is more limited and will never cover all use cases.  You are correct in switching to the bracket syntax.
