### ISSUE TITLE
Partial object after filter

### ISSUE THREAD

**Issue by alexcrisafi** [bohnman/squiggly-filter-jackson#13]
I have the following test:

`import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.bohnman.squiggly.Squiggly;
import com.github.bohnman.squiggly.util.SquigglyUtils;
import org.joda.time.LocalDateTime;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;
import java.util.UUID;

public class squigglyTest {
    private ObjectMapper squigglyObjectMapper;
    private MyObject myObject;

    @Before
    public void setUp() throws IOException {
        myObject = new MyObject();
        myObject.setId(UUID.randomUUID());
        myObject.setRequestedDate(new LocalDateTime());
        myObject.setDetails(new Details());
        myObject.getDetails().setAddress(new Address());
        myObject.getDetails().getAddress().setAddressLine1("East Streen");
        myObject.getDetails().getAddress().setAddressLine2("line2 address");
        myObject.getDetails().getAddress().setRegion("region");
        myObject.getDetails().getAddress().setCity("London");
        myObject.getDetails().getAddress().setPostalCode("E32TD");
        myObject.getDetails().getAddress().setCountry("GB");
    }

    @Test
    public void testSquiggly() {
        String filter = "details.address";
        squigglyObjectMapper = Squiggly.init(new ObjectMapper(), filter);
        System.out.print(SquigglyUtils.stringify(squigglyObjectMapper, myObject));
    }

    private class MyObject {
        Details details;
        private UUID id;
        private LocalDateTime requestedDate;

        @JsonProperty("id")
        public UUID getId() {
            return id;
        }

        public void setId(UUID id) {
            this.id = id;
        }

        @JsonProperty("details")
        public Details getDetails() {
            return details;
        }

        public void setDetails(Details details) {
            this.details = details;
        }

        @JsonProperty("requested_at")
        @JsonFormat(
                pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
        )
        public LocalDateTime getRequestedDate() {
            return requestedDate;
        }

        public void setRequestedDate(LocalDateTime requestedDate) {
            this.requestedDate = requestedDate;
        }
    }

    private class Details {
        private Address address;

        @JsonProperty("address")
        public Address getAddress() {
            return address;
        }

        public void setAddress(Address address) {
            this.address = address;
        }
    }

    private class Address {
        private String company;
        private String addressLine1;
        private String addressLine2;
        private String addressLine3;
        private String region;
        private String city;
        private String postalCode;
        private String country;

        @JsonProperty("company")
        public String getCompany() {
            return company;
        }

        public void setCompany(String company) {
            this.company = company;
        }

        @JsonProperty("line_1")
        public String getAddressLine1() {
            return addressLine1;
        }

        public void setAddressLine1(String addressLine1) {
            this.addressLine1 = addressLine1;
        }

        @JsonProperty("line_2")
        public String getAddressLine2() {
            return addressLine2;
        }

        public void setAddressLine2(String addressLine2) {
            this.addressLine2 = addressLine2;
        }

        @JsonProperty("line_3")
        public String getAddressLine3() {
            return addressLine3;
        }

        public void setAddressLine3(String addressLine3) {
            this.addressLine3 = addressLine3;
        }

        @JsonProperty("region")
        public String getRegion() {
            return region;
        }

        public void setRegion(String region) {
            this.region = region;
        }

        @JsonProperty("city")
        public String getCity() {
            return city;
        }

        public void setCity(String city) {
            this.city = city;
        }

        @JsonProperty("postal_code")
        public String getPostalCode() {
            return postalCode;
        }

        public void setPostalCode(String postalCode) {
            this.postalCode = postalCode;
        }

        @JsonProperty("country")
        public String getCountry() {
            return country;
        }

        public void setCountry(String country) {
            this.country = country;
        }
    }
}`

When I run it I get {"details":{"address":{"company":null,"region":"region","city":"London","country":"GB"}}}

Not expecting to get a partial Address object as a result, but an empty address object instead.

Thanks, 
Alex

**Comment by bohnman** [comment]
Hi Alex,

In order to get an empty address object, you would set your filter to "details.address{}" or "details.address[]".  By default, Squiggly includes what it calls base fields, which are fields that are not annotated with a @PropertyView annotation. 

However,  you did uncover a bug.  I was expecting to see all of the fields printed.  It appears that when a property is annotated with @JsonProperty where the value is different that the actual bean property, it does not get picked up.  I will create a separate issue for this.

Thanks!

~Ryan

**Comment by bohnman** [comment]
@alexcrisafi I just released version 1.3.6, which will now consider `@JsonProperty` annotations.

Also, you can disable including "base" fields on nested objects by default by setting `filter.implicitlyIncludeBaseFields=false` in squiggly.properties.

Please let me know if this resolves the issue for you.

**Comment by alexcrisafi** [comment]
Awesome! Thank you Ryan!
