### ISSUE TITLE
spring-boot: default MappingJackson2HttpMessageConverter not using pre-configured ObjectMapper

### ISSUE THREAD

**Issue by laur89** [bohnman/squiggly-filter-jackson#15]
When we don't explicitly create our own `MappingJackson2HttpMessageConverter`, using pre-initialized `ObjectMapper`, then the converter provided by boot will be built with mapper that apparently doesn't get initialized, meaning the squiggly filter is not registered.

Should we always define our own converter bean?

**Comment by laur89** [comment]
Nah man, all is good. Just wanted to double-check, as documentation & examples didn't work as I'd expect boot to work. I'd recommend users define their own converters from a `@Configuration` class:

```    @Bean
    public HttpMessageConverters customConverters( final ObjectMapper objectMapper ) {
        return new HttpMessageConverters(
                new MappingJackson2HttpMessageConverter( objectMapper ),
                new YourOwnConverter( objectMapper ),
                ...
        );
    }```

**Comment by bohnman** [comment]
Excellent.  Glad you have a solution!

~Ryan
