### ISSUE TITLE
exclude filter not working when json has array and nested arrays with in the array

### ISSUE THREAD

**Issue by mas222r** [bohnman/squiggly-filter-jackson#29]
Hi,

As my current business complex json filter requirement i have mentioned the below original json how it looks and how the json looks after filter using exclude(-).

**original json :**
 {
"myPersonInfo":[
      {
      "myId":2,
	  "myDetailsInfo": [
	     {
		 "myTitle": "Mr.",
	     "myNickName": "testPerson",
		 "myBirthDate": "2013-03-09"
		 }
	  ],
	  "myDetailsInfo1": [
	     {
		 "myTitle1": "Mr.",
	     "myNickName1": "testPerson",
		 "myBirthDate1": "2013-03-09"
		 }
	  ]
	  }
 ]
}
**filter json** 
{"myPerson":[{"myDetails":[{"myNickName":"testPerson","myBirthDate":"2013-03-09"}]}]}

**expected filter json :**

{
"myPersonInfo":[
      {
      "myId":2,
	  "myDetailsInfo": [
	     {
	     "myNickName": "testPerson",
		 "myBirthDate": "2013-03-09"
		 }
	  ],
	  "myDetailsInfo1": [
	     {
		 "myTitle1": "Mr.",
	     "myNickName1": "testPerson",
		 "myBirthDate1": "2013-03-09"
		 }
	  ]
	  }
 ]
}

Here i would like to know why the nested array exclude is giving only the **filter json** (as mentioned above) rather than the **expected filter json**.

After going through notes it seems the dot notation is not working for nested arrays.
My code looks like below

// test with Map.class
		String fileName="sampleArray2.json";
        Path path = Paths.get(getClass().getClassLoader()
        	     .getResource(fileName).toURI());       
        	   byte[] fileBytes = Files.readAllBytes(path);
        	  String jsonString1 = new String(fileBytes);     
		//ObjectMapper mapper = new ObjectMapper();
		//Map obj = mapper.readValue(jsonString,Map.class);
		**String filter = "-myPersonInfo.myDetailsInfo.myTitle";**
		filterGeneric(jsonString1,filter,MyPersonMain.class);

The above code gives **filter json ( as mentioned above) as a result**.

if i replace my filter like this  ------   **String filter = "myPersonInfo[-myDetailsInfo.myTitle]";**
this will give result as **expected json ( as mentioned above).**

Is it a limitation **to not to use dot notation for array of array exclusion**? 

Kindly help me in understanding and resolving the issue.

Thanks,
Suboor

**Comment by bohnman** [comment]
Thanks for pointing this out.  This is definitely a bug.  I'll work on fixing it soon!

**Comment by mas222r** [comment]
Hi,
I don't know whether i need to ask this... at what time this defect will get fix??

**Comment by bohnman** [comment]
Maybe this weekend.  I work on this in my free time, so it just depends if I have free time  :-)

**Comment by bohnman** [comment]
didn't quite work out this weekend...I'll try in the next couple of days.

**Comment by mas222r** [comment]
i got one more scenario **where nested objects excludes also not working** . please find the sample, expected, and actual results below.

**sample original json** :
 {
	"grId": 500018,
	"createDate": "2014-09-12",
	"thesis": {
		"topic": "UNUSED",
		"numberOfThesis": 14,
		"dateOfLec": "2015-01-09",
		"identifier": {
			"identifierType": "id",
			"identifierValue": "id"
		}
	},
	"latestThesisId": 90,
	"thesisIds": [
		23,
		24,
		25
	],
	"identificationNumbers": [
		{
			"type": "20",
			"value": "RWREWREWRW5433"
		}
	],
	"distinguishingFeatures": [
		{
			"feature": "Fourth",
			"position": "Lower"
		},
		{
			"feature": "Third",
			"position": "Higher"
		}
	],
 "myPerson":[
      {
      "myId":2,
	  "myDetails": [
	     {
		 "myTitle": "Mr.",
	     "myNickName": "testPerson",
		 "myBirthDate": "2013-03-09"
		 }
	  ]
	  }
 ]
}

**Exclude scenario is  : -thesis.identifier.identifierType**
**actual result getting :** 

{
	"grId": 500018,
	"createDate": "2014-09-12",
	"thesis": {
		"identifier": {
			"identifierValue": "id"
		}
	},
	"latestThesisId": 90,
	"thesisIds": [23, 24, 25],
	"identificationNumbers": [{
			"type": "20",
			"value": "RWREWREWRW5433"
		}
	],
	"distinguishingFeatures": [{
			"feature": "Fourth",
			"position": "Lower"
		}, {
			"feature": "Third",
			"position": "Higher"
		}
	],
	"myPerson": [{
			"myId": 2,
			"myDetails": [{
					"myTitle": "Mr.",
					"myNickName": "testPerson",
					"myBirthDate": "2013-03-09"
				}
			]
		}
	]
}

**expected result is :** 
{
	"grId": 500018,
	"createDate": "2014-09-12",
	**"thesis": {
                "topic": "UNUSED",
		"numberOfThesis": 14,
		"dateOfLec": "2015-01-09",
		"identifier": {
			"identifierValue": "id"
		}
	}**,
	"latestThesisId": 90,
	"thesisIds": [23, 24, 25],
	"identificationNumbers": [{
			"type": "20",
			"value": "RWREWREWRW5433"
		}
	],
	"distinguishingFeatures": [{
			"feature": "Fourth",
			"position": "Lower"
		}, {
			"feature": "Third",
			"position": "Higher"
		}
	],
	"myPerson": [{
			"myId": 2,
			"myDetails": [{
					"myTitle": "Mr.",
					"myNickName": "testPerson",
					"myBirthDate": "2013-03-09"
				}
			]
		}
	]
}

**Comment by bohnman** [comment]
Hi @mas222r ,

I got around to addressing this issue.  I have it fixed in master.  Do you want to try it out before I cut a new release?

~Ryan

**Comment by bohnman** [comment]
I just release version 1.3.9 which fixes this issue.  Closing.

**Comment by mas222r** [comment]
I have tested few of the scenarios with version 1.3.10. Almost all are passing in my TDD only one is failing .

Below is the scenario : 
json against which test is tested
[test.txt](https://github.com/bohnman/squiggly-java/files/1938297/test.txt)


include : companyList.companySubGroupNames.companySubGrpGivenNames,companyList.directorsDetails,companyList.type

exclude : 
companyList.companySubGroupNames.companySubGrpGivenNames.createdDate,companyList.directorsDetails.qualifications

giving unexpected result : as attached
[test-unexpected.txt](https://github.com/bohnman/squiggly-java/files/1938299/test-unexpected.txt)

Expected result is : 
[test-expected.txt](https://github.com/bohnman/squiggly-java/files/1938300/test-expected.txt)
