### ISSUE TITLE
Filter match case

### ISSUE THREAD

**Issue by XiaoSK** [bohnman/squiggly-filter-jackson#3]
Object: same as README.md

Filter:
`reporter|assignee{firstName,lastName},properties{priority,email},actions{user{firstName,lastName},id,text,type},id,issueDetails,issueSummary`

Only get id,issueDetails,issueSummary in result. Is there something wrong in my filter?

**Comment by bohnman** [comment]
I actually get the correct json when I applied the filter you provided:

`
filter("reporter|assignee{firstName,lastName},properties{priority,email},actions{user{firstName,lastName},id,text,type},id,issueDetails,issueSummary");
 System.out.println(stringify());
`

prints

`
{
  "id": "ISSUE-1",
  "issueSummary": "Dragons Need Fed",
  "issueDetails": "I need my dragons fed pronto.",
  "reporter": {
    "firstName": "Daenerys",
    "lastName": "Targaryen"
  },
  "assignee": {
    "firstName": "Jorah",
    "lastName": "Mormont"
  },
  "actions": [
    {
      "id": null,
      "type": "COMMENT",
      "text": "I'm going to let Daario get this one..",
      "user": {
        "firstName": "Jorah",
        "lastName": "Mormont"
      }
    },
    {
      "id": null,
      "type": "CLOSE",
      "text": "All set.",
      "user": {
        "firstName": "Daario",
        "lastName": "Naharis"
      }
    }
  ],
  "properties": {
    "email": "motherofdragons@got.com",
    "priority": "1"
  }
}
`

Two things:

1) What version of squiggly filter are using?
2) Can you provide the code you were using to test with?

**Comment by XiaoSK** [comment]
```xml
<dependency>
            <groupId>com.github.bohnman</groupId>
            <artifactId>squiggly-filter-jackson</artifactId>
            <version>1.1.2</version>
</dependency>
```
```
com.alibaba.fastjson.JSONObject modelJSON = com.alibaba.fastjson.JSON.parseObject(input);  // the JSON same as README
String filter = "reporter|assignee{firstName,lastName},properties{priority,email},actions{user{firstName,lastName},id,text,type},id,issueDetails,issueSummary";
ObjectMapper objectMapper = Squiggly.init(new ObjectMapper(), filter);
System.out.println(SquigglyUtils.stringify(objectMapper, object));
```

**Comment by bohnman** [comment]
Hmm...I'm still getting the right JSON even pasting your code:

```
public static void main(String[] args) {

        String input="{\"id\":\"ISSUE-1\",\"issueSummary\":\"Dragons Need Fed\",\"issueDetails\":\"I need my dragons fed pronto.\",\"reporter\":{\"firstName\":\"Daenerys\",\"lastName\":\"Targaryen\"},\"assignee\":{\"firstName\":\"Jorah\",\"lastName\":\"Mormont\"},\"actions\":[{\"id\":null,\"type\":\"COMMENT\",\"text\":\"I'm going to let Daario get this one.\",\"user\":{\"firstName\":\"Jorah\",\"lastName\":\"Mormont\"}},{\"id\":null,\"type\":\"CLOSE\",\"text\":\"All set.\",\"user\":{\"firstName\":\"Daario\",\"lastName\":\"Naharis\"}}],\"properties\":{\"priority\":\"1\",\"email\":\"motherofdragons@got.com\"}}";
        com.alibaba.fastjson.JSONObject modelJSON = com.alibaba.fastjson.JSON.parseObject(input);  // the JSON same as README
        String filter = "reporter|assignee{firstName,lastName},properties{priority,email},actions{user{firstName,lastName},id,text,type},id,issueDetails,issueSummary";
        ObjectMapper objectMapper = Squiggly.init(new ObjectMapper(), filter);
        System.out.println(SquigglyUtils.stringify(objectMapper, modelJSON));
    }
```

prints

`
{"reporter":{"lastName":"Targaryen","firstName":"Daenerys"},"id":"ISSUE-1","assignee":{"lastName":"Mormont","firstName":"Jorah"},"properties":{"email":"motherofdragons@got.com","priority":"1"},"issueDetails":"I need my dragons fed pronto.","issueSummary":"Dragons Need Fed","actions":[{"id":null,"text":"I'm going to let Daario get this one.","type":"COMMENT","user":{"lastName":"Mormont","firstName":"Jorah"}},{"id":null,"text":"All set.","type":"CLOSE","user":{"lastName":"Naharis","firstName":"Daario"}}]}
`

1) What version of jackson-databind are you using?
2) If you could attach a working example project that reproduces the issue, that would be great.

**Comment by XiaoSK** [comment]
jackson-core@2.6.4

jackson-databind@2.6.4

jackson-annotations@2.6.0
