### ISSUE TITLE
applying filters on GET request along with other query parameters

### ISSUE THREAD

**Issue by abedultamimi** [bohnman/squiggly-filter-jackson#5]
am trying squiggly with dropwizard integration but when i pass fields query parameter am not able to pass other query paramters.
 for example:
original call is /api/product?id=1
call am trying is:
/api/product?id=1&fields=id,name,price 

this call works though:
/api/product?fields=id,name,price

**Comment by bohnman** [comment]
A couple of questions

1) What version of dropwizard are you using?

2) What are you getting back in the response when you specify both the id and fields?  (eg. empty json or 404, etc.)

**Comment by abedultamimi** [comment]
am using dropwizard 1.0
and i got 200 responses with an empty result

**Comment by bohnman** [comment]
Could you please provide the json that you get when you just provide the id param and not the filter param?

**Comment by abedultamimi** [comment]
{
  "id": "1",
  "name": "dhc default",
  "group": "individual",
  "price": "175.0",
  "creator": { "id": "1", "name": "admin"}
}

**Comment by bohnman** [comment]
I can't replicate the issue.  I have attached an example project that shows it working with Dropwizard 1.0.0

[helloworld.zip](https://github.com/bohnman/squiggly-filter-jackson/files/800134/helloworld.zip)

To run the example:

- unzip
- change to directory
- mvn package
- java -jar target/helloworld-1.0-SNAPSHOT.jar 
- Go in your browser or curl http://localhost:8080/hello-world?name=foo&fields=content

If you want, you can use this project to provide an example replicating the issue.

**Comment by abedultamimi** [comment]
well, many thanks for the detailed example. you are right the issue my normal response comes wrapped as results and rows count as map style
{"results":{"rows":6,"data":[{"id":1,"name":"dhc default" ...

so i corrected my query and things worked as expected:
/api/product?id=1&fields={rows,data{id,code,name,type{name}}}

Thanks again, one more question is there is any away to put in the excluded fields and get everything else

**Comment by bohnman** [comment]
Here's something to consider.  We have a similar situation where I work where we wrap all our list responses in a class called ListResponse.  The json looks like: {"items": [{"id":1}, {"id":2}]}.   Instead of always having to specify fields=items{id}, we customize Squiggly so that we only have to specify fields=id.

Here's the code to do this if you wanted to do something similar:

```java
Squiggly.init(this, new RequestSquigglyContextProvider() {
    @Override
    protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
        if (filter != null && ListResponse.class.isAssignableFrom(beanClass)) {
            filter = "items{" + filter + "}";
        }

        return filter;
    }
});
```

As far as excluding fields, it's described in the README located [here](https://github.com/bohnman/squiggly-filter-jackson#-excluding-fields).
