### ISSUE TITLE
Support for @JsonView Jackson annotation

### ISSUE THREAD

**Issue by zyflix** [bohnman/squiggly-filter-jackson#9]
Our POJO/Models already used @JsonView annotation to filter fields. We want to add Squiggly in our application to enhance existing solution (dynamically filter the fields) , but it seem Squiggly ignore @JsonView annotation. Do you have any solution for this issue ?

**Comment by bohnman** [comment]
Trying to make sure I understand what you are saying.

Give the following setup:

```java
public class View1() {}
public class View2() {}

public class OuterBean {
   @JsonView(View1.class)
   private String id

   @JsonView(View2.class)
   private InnerBean innerBean() {}
}

public class InnerBean() { private String firstName; private String lastName}
```

You would like to be able to specify something like:
```
/outerBeans?fields=View2
```

This would result in something the following:

```json
[{ "innerBean": {"firstName": "", "lastName": ""}}]
```

Is this a correct assumption?

**Comment by zyflix** [comment]
I would like to use Squiggly as second level filtering. Based on example below:

Country model with JsonView annotation
```
@Entity
@Table(name = "afc_ctry")
public class AFCCtry implements Serializable {

    @JsonView(Views.AFCCtry.class)
    @Id
    private String countryCode;

    @JsonView(Views.AFCCtry.class)
    private String fullDesc;

    @JsonView(Views.AFCCtry.class)
    @JoinColumn(name = "currency_code", referencedColumnName = "currency_code")
    private AFCCurr currencyHasOne;

}
```
Currency model with JsonView annotation
```
@Entity
@Table(name = "afc_curr")
public class AFCCurr implements Serializable {

    @JsonView({Views.AFCCurr.class, Views.Association.class})
    @Id
    private String currencyCode;

    @JsonView({Views.AFCCurr.class, Views.Association.class})
    private String fullDesc;

    @JsonView(Views.AFCCurr.class)
    private BigDecimal currencyRate;

}
```
JSON Views setup
```
public class Views {
    public interface Association {}
    public interface AFCCtry extends Association {}
    public interface AFCCurr extends Association {}
}
```
We use this code to register a serializer for Page object
```
@Configuration
public class JsonSerializerConfig {

    @SuppressWarnings("rawtypes")
    @Bean
    public static Module springDataPageModule() {
        return new SimpleModule().addSerializer(Page.class, new JsonSerializer<Page>() {
            @Override
            public void serialize(Page value, JsonGenerator gen, SerializerProvider serializers) throws IOException {
                gen.writeStartObject();
                gen.writeNumberField("totalElements", value.getTotalElements());
                gen.writeFieldName("content");
                serializers.defaultSerializeValue(value.getContent(), gen);
                gen.writeEndObject();
            }
        });
    }

}
```
In controller we add @JsonView(Views.AFCCtry.class) annotation to return the desired output
```
    @JsonView(Views.AFCCtry.class)
    @GetMapping("/countries")
    public ResponseEntity<Page<AFCCtry>> findAll(
            @RequestParam(value = "page", defaultValue = "1") int page,
            @RequestParam(value = "size", defaultValue = "50") int size,
            @RequestParam(value = "direction", defaultValue = "desc") String direction,
            @RequestParam(value = "property", defaultValue = "updateDate") String property
    )  {
        Page<AFCCtry> items = AFCCtryService.findAll(page, size, direction, property);
        return new ResponseEntity<>(items, HttpStatus.OK);
    }
```
Desired output
```
{
   "totalElements":1,
   "content":[
      {
         "countryCode":"MYS",
         "fullDesc":"MALAYSIA",
         "currencyHasOne":{
            "currencyCode":"MYR",
            "fullDesc":"MALAYSIAN RINGGIT"
         }
      }
   ]
}
```
Now we would like to use Squiggly and issue url below to apply additional filtering. In this case remove `currencyHasOne`
```
/countries?fields=-currencyHasOne
```
and the expected output will be
```
{
   "totalElements":1,
   "content":[
      {
         "countryCode":"MYS",
         "fullDesc":"MALAYSIA"
      }
   ]
}
```
Hopefully you understand what are we trying to achieve.

Thank you.

**Comment by bohnman** [comment]
Can you please provide the code where you initialize Squiggly?

**Comment by zyflix** [comment]
Code to initialize Squiggly:

```
@Configuration
public class SquigglyConfig {

    @Bean
    public ObjectMapper objectMapper() {
        return Squiggly.init(new ObjectMapper(), new RequestSquigglyContextProvider() {
            @Override
            protected String customizeFilter(String filter, HttpServletRequest request, Class beanClass) {
                if (filter != null && Page.class.isAssignableFrom(beanClass)) {
                    filter = "content{" + filter + "}";
                }
                return filter;
            }
        });
    }

    @Bean
    public FilterRegistrationBean squigglyRequestFilter() {
        FilterRegistrationBean filter = new FilterRegistrationBean();
        filter.setFilter(new SquigglyRequestFilter());
        filter.setOrder(1);
        return filter;
    }

}
```

**Comment by bohnman** [comment]
Are you getting an error message like the following?

```
"org.springframework.http.converter.HttpMessageNotWritableException","message":"Could not write content: (was java.lang.NullPointerException)
```

**Comment by zyflix** [comment]
One of the problem we are facing is that non-annotated fields or annotated fields with different @JsonView still get serialized by Squiggly. Further investigation, we facing similar problem using Jackson only when we set `spring.jackson.mapper.DEFAULT_VIEW_INCLUSION=true` in `application.properties`. Using or set to `spring.jackson.mapper.DEFAULT_VIEW_INCLUSION=false` will produce expected output. This problem also causing stackoverflow error because of JSON infinite recursion.

**Comment by bohnman** [comment]
I have released version 1.3.4, which fixes a NullPointerException when using @JsonView.  However, I'm not sure this actually addresses your issue.

I have attached a sample Spring Boot project, which uses @JsonView.  It appears to work regardless  of what value you set for spring.jackson.mapper.DEFAULT_VIEW_INCLUSION.

If upgrading to version 1.3.4, does not fix the issue for you, please modify this sample project to reproduce your issue.  Alternatively, you can provide your own example project that exhibits your issue.

[squiggly-spring-boot-jsonview.zip](https://github.com/bohnman/squiggly-filter-jackson/files/979417/squiggly-spring-boot-jsonview.zip)

~Ryan

**Comment by bohnman** [comment]
Hi @zyflix, just checking in to see if you had a chance to try version 1.3.4 as described above.

**Comment by zyflix** [comment]
Hi @bohnman, I got caught up with work lately. I will try it out the next few days.

**Comment by bohnman** [comment]
I'm going to assume this issue is resolved.  If it is not, please re-open this issue.
